apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  ports:
    - port: 4499
      targetPort: 4499
  selector:
    app: wisecow
