apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: ClusterIP
  ports:
    - port: 4499        # The port the service exposes
      targetPort: 4499  # The port the container listens on
  selector:
    app: wisecow
